"""add_jti_to_refresh_tokens

Revision ID: 6dc5bb377ff2
Revises: 284782d7d241
Create Date: 2026-06-07 20:13:34.478954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dc5bb377ff2'
down_revision: Union[str, Sequence[str], None] = '284782d7d241'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('jti', sa.String(length=36), nullable=False))
    op.create_index(op.f('ix_refresh_tokens_jti'), 'refresh_tokens', ['jti'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_tokens_jti'), table_name='refresh_tokens')
    op.drop_column('refresh_tokens', 'jti')
    # ### end Alembic commands ###
